// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace FamousQuotesConsumer.Models
{
    public partial class Quote
    {
        private string _author;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Author
        {
            get { return this._author; }
            set { this._author = value; }
        }
        
        private string _text;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Text
        {
            get { return this._text; }
            set { this._text = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Quote class.
        /// </summary>
        public Quote()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken authorValue = inputObject["Author"];
                if (authorValue != null && authorValue.Type != JTokenType.Null)
                {
                    this.Author = ((string)authorValue);
                }
                JToken textValue = inputObject["Text"];
                if (textValue != null && textValue.Type != JTokenType.Null)
                {
                    this.Text = ((string)textValue);
                }
            }
        }
    }
}
