// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using FamousQuotesConsumer.Models;
using Newtonsoft.Json.Linq;

namespace FamousQuotesConsumer.Models
{
    public static partial class QuoteCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Quote> DeserializeJson(JToken inputObject)
        {
            IList<Quote> deserializedObject = new List<Quote>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Quote quote = new Quote();
                quote.DeserializeJson(iListValue);
                deserializedObject.Add(quote);
            }
            return deserializedObject;
        }
    }
}
