// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using FamousQuotesConsumer;
using Microsoft.Rest;

namespace FamousQuotesConsumer
{
    public partial class FamousQuotes : ServiceClient<FamousQuotes>, IFamousQuotes
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IQuotes _quotes;
        
        public virtual IQuotes Quotes
        {
            get { return this._quotes; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        public FamousQuotes()
            : base()
        {
            this._quotes = new Quotes(this);
            this._baseUri = new Uri("https://microsoft-apiapp775327171cc642fa8a6480cf44abb9a5.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public FamousQuotes(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._quotes = new Quotes(this);
            this._baseUri = new Uri("https://microsoft-apiapp775327171cc642fa8a6480cf44abb9a5.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public FamousQuotes(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._quotes = new Quotes(this);
            this._baseUri = new Uri("https://microsoft-apiapp775327171cc642fa8a6480cf44abb9a5.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public FamousQuotes(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public FamousQuotes(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the FamousQuotes class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public FamousQuotes(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
